### ISSUE TITLE
Installing spaceprime

### ISSUE THREAD

**Issue by kpmercier** [connor-french/spaceprime#35]
### Environment Information

-   spaceprime version: 
-   Python version: 3.12.4
-   Operating System: MacOS Ventura 13.6.7

### Description

I am trying to install spaceprime on macOS but am receiving errors with both conda and pip. 
- conda responds with a package not found error
- pip's error message is a bit more opaque to me, but all the info is below 

### What I Did

```
(base) katie@Anas-iMac ~ % conda activate sp
(sp) katie@Anas-iMac ~ % conda install -c conda-forge spaceprime 
Channels:
 - conda-forge
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - spaceprime

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

```
(base) katie@Anas-iMac ~ % pip install spaceprime
Collecting spaceprime
  Using cached spaceprime-0.0.3-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting numpy (from spaceprime)
  Using cached numpy-2.0.0-cp312-cp312-macosx_10_9_x86_64.whl.metadata (60 kB)
Collecting typing (from spaceprime)
  Using cached typing-3.7.4.3.tar.gz (78 kB)
  Preparing metadata (setup.py) ... done
Collecting msprime (from spaceprime)
  Using cached msprime-1.3.2.tar.gz (901 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting rasterio>=1.0.0 (from spaceprime)
  Using cached rasterio-1.3.10-cp312-cp312-macosx_10_15_x86_64.whl.metadata (14 kB)
Collecting scipy (from spaceprime)
  Using cached scipy-1.14.0-cp312-cp312-macosx_10_9_x86_64.whl.metadata (60 kB)
Collecting shapely (from spaceprime)
  Using cached shapely-2.0.5-cp312-cp312-macosx_10_9_x86_64.whl.metadata (7.0 kB)
Collecting geopandas (from spaceprime)
  Using cached geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)
Collecting scikit-allel (from spaceprime)
  Using cached scikit_allel-1.3.8-cp312-cp312-macosx_10_9_x86_64.whl.metadata (3.1 kB)
Collecting affine (from rasterio>=1.0.0->spaceprime)
  Using cached affine-2.4.0-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs (from rasterio>=1.0.0->spaceprime)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: certifi in /opt/miniconda3/lib/python3.12/site-packages (from rasterio>=1.0.0->spaceprime) (2024.6.2)
Collecting click>=4.0 (from rasterio>=1.0.0->spaceprime)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting cligj>=0.5 (from rasterio>=1.0.0->spaceprime)
  Using cached cligj-0.7.2-py3-none-any.whl.metadata (5.0 kB)
Collecting snuggs>=1.4.1 (from rasterio>=1.0.0->spaceprime)
  Using cached snuggs-1.4.7-py3-none-any.whl.metadata (3.4 kB)
Collecting click-plugins (from rasterio>=1.0.0->spaceprime)
  Using cached click_plugins-1.1.1-py2.py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: setuptools in /opt/miniconda3/lib/python3.12/site-packages (from rasterio>=1.0.0->spaceprime) (69.5.1)
Collecting pyogrio>=0.7.2 (from geopandas->spaceprime)
  Using cached pyogrio-0.9.0.tar.gz (352 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "/opt/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/f9/5zqtc4wj6b9036tp04j51ftc0000gr/T/pip-build-env-wrj6l8w9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/f9/5zqtc4wj6b9036tp04j51ftc0000gr/T/pip-build-env-wrj6l8w9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/f9/5zqtc4wj6b9036tp04j51ftc0000gr/T/pip-build-env-wrj6l8w9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 154, in <module>
        File "<string>", line 129, in get_gdal_config
        File "<string>", line 85, in get_gdal_config
        File "<string>", line 39, in read_response
        File "/opt/miniconda3/lib/python3.12/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/lib/python3.12/subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/lib/python3.12/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/opt/miniconda3/lib/python3.12/subprocess.py", line 1955, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by connor-french** [comment]
Ope! It's still not up on conda and I think I've fixed the pip problem. I'm planning a new release, but for now I'd try installing from git:

```
pip install git+https://github.com/connor-french/spaceprime
```

Let me know if that doesn't work. I'm planning to push a release in the next few days and adding it to conda.

**Comment by kpmercier** [comment]
Thanks! I tried installing from git but receive the same error. 

```
(base) katie@Anas-iMac ~ % pip install git+https://github.com/connor-french/spaceprime     
Collecting git+https://github.com/connor-french/spaceprime
  Cloning https://github.com/connor-french/spaceprime to /private/var/folders/f9/5zqtc4wj6b9036tp04j51ftc0000gr/T/pip-req-build-8qz3gncs
  Running command git clone --filter=blob:none --quiet https://github.com/connor-french/spaceprime /private/var/folders/f9/5zqtc4wj6b9036tp04j51ftc0000gr/T/pip-req-build-8qz3gncs
  Resolved https://github.com/connor-french/spaceprime to commit 78e22bc3d00c47cd190e39712e7cfe23f08ca9f5
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy<2 (from spaceprime==0.0.3)
  Using cached numpy-1.26.4-cp312-cp312-macosx_10_9_x86_64.whl.metadata (61 kB)
Collecting typing (from spaceprime==0.0.3)
  Using cached typing-3.7.4.3.tar.gz (78 kB)
  Preparing metadata (setup.py) ... done
Collecting msprime (from spaceprime==0.0.3)
  Using cached msprime-1.3.2.tar.gz (901 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting rasterio>=1.0.0 (from spaceprime==0.0.3)
  Using cached rasterio-1.3.10-cp312-cp312-macosx_10_15_x86_64.whl.metadata (14 kB)
Collecting scipy (from spaceprime==0.0.3)
  Using cached scipy-1.14.0-cp312-cp312-macosx_10_9_x86_64.whl.metadata (60 kB)
Collecting shapely (from spaceprime==0.0.3)
  Using cached shapely-2.0.5-cp312-cp312-macosx_10_9_x86_64.whl.metadata (7.0 kB)
Collecting geopandas (from spaceprime==0.0.3)
  Using cached geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)
Collecting scikit-allel (from spaceprime==0.0.3)
  Using cached scikit_allel-1.3.8-cp312-cp312-macosx_10_9_x86_64.whl.metadata (3.1 kB)
Collecting contextily (from spaceprime==0.0.3)
  Using cached contextily-1.6.0-py3-none-any.whl.metadata (2.9 kB)
Collecting matplotlib (from spaceprime==0.0.3)
  Using cached matplotlib-3.9.1-cp312-cp312-macosx_10_12_x86_64.whl.metadata (11 kB)
Collecting affine (from rasterio>=1.0.0->spaceprime==0.0.3)
  Using cached affine-2.4.0-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs (from rasterio>=1.0.0->spaceprime==0.0.3)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: certifi in /opt/miniconda3/lib/python3.12/site-packages (from rasterio>=1.0.0->spaceprime==0.0.3) (2024.6.2)
Collecting click>=4.0 (from rasterio>=1.0.0->spaceprime==0.0.3)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting cligj>=0.5 (from rasterio>=1.0.0->spaceprime==0.0.3)
  Using cached cligj-0.7.2-py3-none-any.whl.metadata (5.0 kB)
Collecting snuggs>=1.4.1 (from rasterio>=1.0.0->spaceprime==0.0.3)
  Using cached snuggs-1.4.7-py3-none-any.whl.metadata (3.4 kB)
Collecting click-plugins (from rasterio>=1.0.0->spaceprime==0.0.3)
  Using cached click_plugins-1.1.1-py2.py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: setuptools in /opt/miniconda3/lib/python3.12/site-packages (from rasterio>=1.0.0->spaceprime==0.0.3) (69.5.1)
Collecting geopy (from contextily->spaceprime==0.0.3)
  Using cached geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting mercantile (from contextily->spaceprime==0.0.3)
  Using cached mercantile-1.2.1-py3-none-any.whl.metadata (4.8 kB)
Collecting pillow (from contextily->spaceprime==0.0.3)
  Using cached pillow-10.4.0-cp312-cp312-macosx_10_10_x86_64.whl.metadata (9.2 kB)
Requirement already satisfied: requests in /opt/miniconda3/lib/python3.12/site-packages (from contextily->spaceprime==0.0.3) (2.32.2)
Collecting joblib (from contextily->spaceprime==0.0.3)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting xyzservices (from contextily->spaceprime==0.0.3)
  Using cached xyzservices-2024.6.0-py3-none-any.whl.metadata (4.0 kB)
Collecting pyogrio>=0.7.2 (from geopandas->spaceprime==0.0.3)
  Using cached pyogrio-0.9.0.tar.gz (352 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "/opt/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/f9/5zqtc4wj6b9036tp04j51ftc0000gr/T/pip-build-env-i8d_utai/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/f9/5zqtc4wj6b9036tp04j51ftc0000gr/T/pip-build-env-i8d_utai/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/f9/5zqtc4wj6b9036tp04j51ftc0000gr/T/pip-build-env-i8d_utai/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 154, in <module>
        File "<string>", line 129, in get_gdal_config
        File "<string>", line 85, in get_gdal_config
        File "<string>", line 39, in read_response
        File "/opt/miniconda3/lib/python3.12/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/lib/python3.12/subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/miniconda3/lib/python3.12/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/opt/miniconda3/lib/python3.12/subprocess.py", line 1955, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by connor-french** [comment]
Ah, I did some digging and the dependency `pyogrio` has some compatibility issues with python 3.12 (https://github.com/geopandas/pyogrio/issues/416, https://github.com/pyronear/pyro-risks/pull/83#issuecomment-2223547577). I'm setting the required python version to be <3.12 until they get their stuff worked out. For now, I'd recommend creating a conda environment that uses python 3.11, with:

```
conda env create --name myenv --python=3.11
```

and try installing spaceprime from github. Sorry for the headaches! This is a good reminder for me to add testing for 3.12- it's a new python version and some packages haven't upgraded support yet. I just opened a new issue for that, #36

**Comment by kpmercier** [comment]
I was having the same message using older versions of python. Since the error message was related to gdal, I tried using conda to install gdal and then installing spaceprime from github and it worked!

```
conda install -c conda-forge gdal
pip install git+https://github.com/connor-french/spaceprime
```

**Comment by connor-french** [comment]
Oh nice! I've been taking for granted GDAL being installed already- it needs to be installed separately beforehand and I've been doing that without thinking. I need to add this to the installation documentation. Thanks for opening an issue!
